# Generated by Django 4.2.4 on 2023-09-03 14:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfCategory', models.CharField(max_length=100)),
                ('imgOfCategory', models.URLField(blank=True, max_length=10000, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nameOfCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfItem', models.CharField(max_length=100)),
                ('priceOfItem', models.IntegerField()),
                ('imgOfItem', models.URLField(max_length=10000)),
                ('BestsellerItem', models.BooleanField(default=False)),
                ('descriptionOfItem', models.CharField(max_length=2000)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nameOfItem')),
            ],
        ),
    ]
