# Generated by Django 4.2.4 on 2023-10-05 18:21

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfCategory', models.CharField(max_length=100)),
                ('imgOfCategory', models.URLField(blank=True, max_length=10000, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nameOfCategory')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('userPhoneNumber', models.CharField(max_length=10, unique=True)),
                ('userName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('status', models.CharField(default='Workin` at order', max_length=50)),
                ('dataTime', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeApi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfItem', models.CharField(max_length=100)),
                ('priceOfItem', models.IntegerField()),
                ('imgOfItem', models.URLField(max_length=10002)),
                ('BestsellerItem', models.BooleanField(default=False)),
                ('descriptionOfItem', models.CharField(max_length=2000)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nameOfItem')),
                ('categoryOfItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeApi.category')),
            ],
        ),
    ]
