# Generated by Django 4.2.4 on 2023-08-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgOfCategory',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
