# Generated by Django 4.2.4 on 2023-11-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeApi', '0003_alter_item_bestselleritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imgOfItem',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='priceOfItem',
            field=models.FloatField(),
        ),
    ]
