# Generated by Django 4.2.4 on 2023-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeApi', '0005_alter_item_priceofitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='priceOfItem',
            field=models.FloatField(),
        ),
    ]
