# Generated by Django 4.2.4 on 2023-10-03 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeApi', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(limit_choices_to={'userPhoneNumber__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='cakeApi.user', to_field='userPhoneNumber'),
        ),
    ]
